apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: app-ns

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-manager
  namespace: app-ns
rules:
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "create", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager-binding
  namespace: app-ns
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: app-ns
roleRef:
  kind: Role
  name: job-manager
  apiGroup: rbac.authorization.k8s.io
