apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-manager
  namespace: app-ns  # Replace with your namespace if different
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-manager
  template:
    metadata:
      labels:
        app: job-manager
    spec:
      serviceAccountName: vault-auth  
      containers:
        - name: job-manager
          image: adi463/job-manager:5.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: NAMESPACE
              value: "app-ns"  # Replace with your namespace
            - name: JOB_NAME
              value: "app-rolling-restart-lms"  # Replace with your job name
            - name: CRONJOB_NAME
              value: "app-rolling-restart"  # Replace with your cronjob name 
            - name: WAIT_TIME
              value: "3"  
